### ISSUE TITLE
Can I custom PlantUML style by options?

### ISSUE THREAD

**Issue by hapihacking** [nice-move/remark-kroki#5]
styles like ISAAC, Deep Sea, Graytone...etc

**Comment by Airkro** [comment]
嵌入式文档使用 kroki 这种在线服务，对服务本身进行配置，或API传递自定义选项不是好方法。

建议将自定义选项写成代码的一部分，这样你的图表信息是一体便携的，前提是该图表库支持在代码里写选项。

以 PlantUML 为例，使用 !theme 语法：

```plantuml
!theme cerulean

rectangle "Main" {
  (main.view)
  (singleton)
}
...
```

**Comment by Airkro** [comment]
Embedded documentation Using an online service like Kroki, configuring the service itself, or API passing custom options is not a good idea.
It is recommended that custom options be written as part of the code so that your diagram information is portable in one piece, provided that the diagram library supports writing options in code. 
Take PlantUML for example, using `!theme` syntax: 

```plantuml
!theme cerulean

rectangle "Main" {
  (main.view)
  (singleton)
}
...
```

**Comment by hapihacking** [comment]
kroki 本身应该是支持 theme 的

- [Include additional PlantUML themes · Issue #900 · yuzutech/kroki](https://github.com/yuzutech/kroki/issues/900)
- [Use option passing to nominate a PlantUML theme · Issue #897 · yuzutech/kroki](https://github.com/yuzutech/kroki/issues/897)

是不是 remark-kroki 只需要把 kroki 本身提供的 theme配置暴露出来就可以了呢

我没有自建，直接使用的官方服务，所以没办法自己配置 kroki 服务端。

**Comment by Airkro** [comment]
无法理解你的问题，只要在图表文本中加入 `!theme xxx` 就可以使自带的主题生效，这属于 PlantUML [自带的功能](https://plantuml.com/zh/theme)，与 kroki/remark-kroki 无关。

实测远程主题也能生效所以现在是哪里不满足你的场景？

**Comment by Airkro** [comment]
ISAAC, Deep Sea, Graytone 是 [PlantUML-styler](https://github.com/isaaceindhoven/plantuml-styler#plantuml-styler) 的私有实现，PlantUML 并不支持

**Comment by hapihacking** [comment]
这样啊，那我懂了，我以为是kroki自己实现的，谢谢你的解答
